set(GTEST_PATH "${PROJECT_BINARY_DIR}/external/googletest")

message(STATUS "GTEST_PATH : " ${GTEST_PATH})

set(GTEST_LIBRARIES ${GTEST_PATH}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}gtest${CMAKE_STATIC_LIBRARY_SUFFIX})
list(APPEND GTEST_LIBRARIES ${GTEST_PATH}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}gtest_main${CMAKE_STATIC_LIBRARY_SUFFIX})
list(APPEND GTEST_LIBRARIES ${GTEST_PATH}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}gmock${CMAKE_STATIC_LIBRARY_SUFFIX})
list(APPEND GTEST_LIBRARIES ${GTEST_PATH}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}gmock_main${CMAKE_STATIC_LIBRARY_SUFFIX})

message(STATUS "GTEST_LIBRARIES : ${GTEST_LIBRARIES}")

include(ExternalProject)

externalproject_add(GTEST
                    SOURCE_DIR ${PROJECT_SOURCE_DIR}/external/packages/googletest
                    CMAKE_ARGS "-DCMAKE_INSTALL_PREFIX=${PROJECT_BINARY_DIR}/external/googletest"
                    PREFIX ${GTEST_PATH}
                    # INSTALL_DIR ${GTEST_PATH}
                    # BINARY_DIR ${GTEST_PATH}/build
                    LOG_INSTALL)
